### ISSUE TITLE
Parse TODOs (all files) not working

### ISSUE THREAD

**Issue by herkulano** [kantlove/vscode-todo-parser#16]
When executing "Parse TODOs (all files)" the activity monitor in osx shows "code helper" running at +100% and the laptop fans start after a while. It never shows the output and I have to restart and kill the process to manage the CPU.

![screen shot 2016-08-12 at 13 41 41](https://cloud.githubusercontent.com/assets/125300/17620102/8d886aa4-6092-11e6-8ed0-832ba34ecff1.png)

**Comment by kantlove** [comment]
Looks like it takes too long to parse. How large are your files?

**Comment by herkulano** [comment]
It's a fairly big project with hundreds of files. 
Also is there a way not to parse /node_modules, /bower_components, /dist, etc?

**Comment by kantlove** [comment]
There is. Just include the folder name in your User Setting like this
```
"TodoParser": {
  "folderExclude": ["node_modules", "bower_components", "dist"]
}
```
Could you try it out and tell me the result?

**Comment by herkulano** [comment]
The problem persists.

```js
"TodoParser": {
    "exclude": [
      "java",
      "c",
      "cpp", "h", "hpp",
      "cs",
      "py",
      "coffee",
      "ada", "adb",
      "hs", "lhs",
      "rb",
      "go",
      "fs", "fsx",
      "r",
      "pl", "PL",
      "lua"
    ],
    "folderExclude": [
      ".vscode",
      "node_modules",
      "bower_components",
      "dist"
    ],
    "markers": [
      "NOTE:",
      "FIXME:",
      "REMINDER:"
    ]
  },
```

**Comment by kantlove** [comment]
Well, it is confirmed to be a performance issue. Currently, I use RegEx to parse each file. Looks like that is still not good enough.

I'm looking into this but it will take some time to solve though. Thank you for reporting this :+1:

**Comment by j-hogue** [comment]
I am also experiencing this issue.  Side note about settings and how to limit files included in the search, instead of `exclude` files to use `include` files, I think that would be a much shorter list?

Thanks for you efforts, this is a very useful utility.

**Comment by kantlove** [comment]
I have added some changes in [v1.8.0-beta](https://github.com/kantlove/vscode-todo-parser/releases/tag/v1.8.0-beta) to support large projects. I also added an `include` entry in settings to specify which file extension should be parsed. Concretely:
- The extension now parse a chunk of files instead of *all-at-once*.
- You will see the result in the panel one after another.
- The progress is displayed on the status bar (bottom). Clicking on it will **cancel** the task.

It would be very nice if you guys can test the included *.vsix file before I release it.  It should take you only 1min. The steps should be:
- Download the vsix package [here](https://github.com/kantlove/vscode-todo-parser/releases/tag/v1.8.0-beta).
- Uninstall the extension.
- Run `code vscode-todo-parser-1.8.0-beta.vsix`

(or you can follow the instruction on the [official page](https://code.visualstudio.com/docs/extensions/install-extension#_install-a-packaged-extension-vsix))

Thank you :+1:

**Comment by herkulano** [comment]
Tried it with the project that was having problems and it works really well 💯 
The `include` option is a really nice addition.

Thank you!
