### ISSUE TITLE
Avoid triggering other extensions when read file content.

### ISSUE THREAD

**Issue by kantlove** [kantlove/vscode-todo-parser#23]
Moved here from #19.
> When I run "ParseTODOs (all files)" all files are processed to find TODOs but in the same time other TS Code extensions are invoked - namely "Stylelint" and "Spelling and Grammar Checker" and they process those files also. It is a very frustrating effect.

**Comment by mlc-mlapis** [comment]
Thank you for moving. I did not know that this efect could happen by default.

**Comment by kantlove** [comment]
Unfortunately, after some investigation, I don't think this is possible at the moment.
The reason is that the extension relies on the API provided by Vscode to identify the language of a file. And there is no other suitable way I know to accomplish the task.

**Comment by mlc-mlapis** [comment]
Hmm, not good. I do not understand only exactly why this is happening when the setting is:

```
"TodoParser": {
        "exclude": [],
        "include": ["ts"],
        "folderExclude": ["node_modules", ".vscode", "typings"],
        "markers": ["@todo"]
}
```

There are included only TS source files so I suppose that you touch only them and not others like CSS?

Thanks for your answer.

**Comment by kantlove** [comment]
Oh, sorry. Here is a more detail explanation.
During the process, I call an API to open a file for me. Something like this:
```typescript
workspace.openTextDocument(path).then(
  function (doc: TextDocument) {
    let lang = doc.languageId; // now, I can get the language
```
It's nice and simple. However, it also triggers other extensions related to the file (not 100% sure!).
If I manually open the file myself. Something like this:
```typescript
fs.readFile(path, function(err, data) {
  // languageId?
});
```
Nothing is triggered! But now I'll have to detect the language by myself. 
This is where I'm stuck. Have tried some npm modules but it does not work as expected.

**Comment by mlc-mlapis** [comment]
Ok, thank you for explanation. By TS I meant *.ts files really. I was related to the line of config (that i want check only these files):
```
"include": ["ts"],
```

If understand correctly, there is currently possible to do:
1. Using fs.readFile to check file extensions on your own + using VS Code API function getLanguages(): Thenable<string[]> + your own config property (..., include, ...) which specifies what to check.
2. Accept that all associated extension on filtered and checked files (point #1) will run in this moment because of the actual functionality of API: openTextDocument(fileName: string): Thenable<TextDocument>.
3. Report a new issue (as a bug or a new feature?) to VS Code development team to ask for a solution - maybe a new parameter on openTextDocument function will be necessary that will allow to open a file in "read only mode" (as you need in our case) without invoking anything else.

All above sounds reasonable, I think. What do you think?

**Comment by kantlove** [comment]
For 1, there is a problem with languages that share a common file extension (e.g. C and C++ with *.h). 
I reported an issue on VS Code repo [here #11424](https://github.com/Microsoft/vscode/issues/11424)

**Comment by mlc-mlapis** [comment]
For 1, you are right but this problem has not probably any solution except using some extra special convention like "myfilename.sufix.h" and then would have sense not to use "getLanguages()" at all, and use config properties only. Users would filter their files like ["sufix.h"] then.

Thanks for reporting the issue. We will see ...

**Comment by kantlove** [comment]
Looks like that's the way it is right now.

**Comment by mlc-mlapis** [comment]
Hmm, I understand the explanation about caching (https://github.com/Microsoft/vscode/issues/11424) but the mention about "the consumer of the open event should be prepared for this" is a bit not understandable.

Did @jrieken mean that every extension has to know how to react to these type of event invoked by another extension?

The main problem with invoking many extension on "openTextDocument" is that after running "ParseTODOs (all files)" the info about errors and warnings on the status bar of VS Code is overloaded
![image](https://cloud.githubusercontent.com/assets/5693835/18198744/9ff15540-70fd-11e6-9903-d05a9688bd1b.png) and the only way is close and re-open VS Code then = very frustrating.

**Comment by kantlove** [comment]
I think he means that the users/developers have to understand that that's the way it works atm.
Yep, I will add "folderInclude" in the next version.

**Comment by mlc-mlapis** [comment]
Thanks a lot.
