### ISSUE TITLE
Habillity to accept "@TODO"

### ISSUE THREAD

**Issue by leocaseiro** [kantlove/vscode-todo-parser#60]
First of all, many thanks for this awesome plugin.

I was wondering if we could be able to parse `@TODO` as well.

I use [TODO as JSDocs](http://usejsdoc.org/tags-todo.html) and I have to remove `@` to be able to read on the list.

Thanks

**Comment by kantlove** [comment]
Hi @leocaseiro, thanks for your kind words.

To use `@TODO`, you can add it to the extension setting in VSCode (see [this](https://github.com/kantlove/vscode-todo-parser#settings))

Another problem is even after adding the setting, it will not work yet. Because you are using multi-line comment, and there is a bug:
```javascript
/** <-- bug is here
 * @todo Write the documentation.
....
```
The extension cannot recognize multi-line comments starting with `\**`, but it can with `\*` (one asterisk) (also see #58).

And this will be fixed in v1.8.10 👍

**Comment by leocaseiro** [comment]
Thanks @kantlove! It worked for me!
